### ISSUE TITLE
Stop Audio Playback?

### ISSUE THREAD

**Issue by ashes999** [josuigoa/CameraMic#10]
Hi,

Is there a way to stop the audio playback?

I found a [stopAudio method on CameraMic.java](https://github.com/josuigoa/CameraMic/blob/master/dependencies/android/src/org/haxe/extension/cameramic/CameraMic.java#L207) but it [doesn't seem to be defined on the C++ interface](https://github.com/josuigoa/CameraMic/blob/master/project/common/ExternalInterface.cpp).

This is a big problem for my app: I need to terminate long recordings gracefully when users navigate away from the recording area.

Is there any chance you could add a stop-playback method?

**Comment by josuigoa** [comment]
Hi,

I've done some changes and it should work. I'm not sure, because I'm not able to try it right now. Could you try and tell me?

**Comment by ashes999** [comment]
Hi,

I'm not at my usual dev box. I can try this tonight (in the next ~10-12 hours approximately) and I'll get back to you and let you know.

Thanks for addressing this so quickly.

**Comment by ashes999** [comment]
Sorry about the delay. It works, sort of; I got some JNI crashes that I didn't check the stacks of.

It seems to me that in `stopAudio`, you just [call methods on mPlayer](https://github.com/josuigoa/CameraMic/blob/master/dependencies/android/src/org/haxe/extension/cameramic/CameraMic.java#L209) without checking if it's not null. In my app, because of the way I have to make sure there's only ever one thing playing at a time, I call `stopAudio` before I ever played the audio; I'm pretty sure `mPlayer` is null. (You can see the same logic in `stopRecordingAudio`).

If I account for this in my code, it seems to work consistently for me.

Do you mind adding some if-null checks to the Java code? That would really make it easier for me to use.

**Comment by josuigoa** [comment]
oh! I thought about that case too late... sorry. I've added the checks so I hope now it works without crashes

**Comment by ashes999** [comment]
I can confirm that with the latest version, with my work-around removed, it doesn't crash any more. I guess that really was the problem.

Thanks again for doing this, I really appreciate it.
