### ISSUE TITLE
Unknown identifier: CameraMic

### ISSUE THREAD

**Issue by ashes999** [josuigoa/CameraMic#3]
Hi,

I tried cloning your repository and building `test_project`, as well as importing it has a haxelib into another project. Whenever I compile, I get copies of this error:

`Unknown identifier: CameraMic`

I tried tweaking the CameraMic class to add a package name (eg. `cm`), but this didn't fix the problem either.

**Comment by josuigoa** [comment]
Hi!
could you show me the output of ´haxelib list´ command, please? It seems that the lib path is not correct

**Comment by ashes999** [comment]
Hi,

Here's the output:

```
actuate: [1.7.5]
CameraMic: git [dev:C:\dev\nme\haxe210\Haxe\lib\CameraMic/git]
flixel: [3.3.6]
haxe-ga: [0.4.16]
hxcpp: [3.1.48]
lime: [2.0.4]
linden-flurry: git [dev:C:\dev\nme\haxe210\Haxe\lib\linden-flurry/git]
openfl-samples: [2.2.0]
openfl: [2.2.0]
swf: [1.7.3]
```

I installed your library with `haxelib git CameraMic https://github.com/josuigoa/CameraMic`

**Comment by josuigoa** [comment]
Hi!

When you run the 'haxelib git CameraMic' command, you download all the
repo, the library and the test project. Haxelib is now looking for the lib
in the repo directory. You must point to the lib directory. To set that
path:

haxelib dev CameraMic c:.../CameraMic/git/CameraMic
2015 urt 4 05:37 igorleak hau idatzi du ("Ashiq A." <
notifications@github.com>):

**Comment by ashes999** [comment]
Hi,

I see. Unlike other projects on GitHub, you have your `haxelib.json` in a sub-directory instead of in the GitHub repository root. 

I even see now that you do have something in the readme about this :)

It would be great if this wasn't necessary, like other projects on GitHub. Thanks for your help. I will re-test and confirm that this fixes my issue.

**Comment by josuigoa** [comment]
You're right, it would be better if it could be installed the lib directly with haxelib git command. I'll probably take the sub-dir content to the root.

Thanks for the suggestion!
