### ISSUE TITLE
test_project silently fails

### ISSUE THREAD

**Issue by ashes999** [josuigoa/CameraMic#4]
Hi,

I can't seem to get your `test_project` to build and run as a `flash` app. It just shows me a white screen.

I dug a bit into your code. It seems like this line, fairly early on in the initialization, causes the app to error out:

`CameraMic.appFilesDirectory = "/cameraMicTest";`

I tried replacing this with a Windows path to a real (empty) directory, but that didn't do anything. I dug a bit into your code, but didn't see any issues with your property setter.

Am I doing something wrong (again?) :)

**Comment by josuigoa** [comment]
Hi!

this library only works for android & ios for now.

It's not planned to work in the other platforms, but I not even think about that, maybe in the future... :)

**Comment by ashes999** [comment]
Hi,

That makes sense. What confused me were the `import flash.display.Blah` statements I saw. I thought you intended it to work on Flash.

What do I set the appFilesDirectory to? Do I need root permission to create the directory? How does this work with a non-jailbroken phone?

**Comment by josuigoa** [comment]
When I created the extension, I had a rooted phone and it worked properly. Now I just tested with my non-rooted android phone and it worked.

You can see [here](https://github.com/josuigoa/CameraMic/blob/master/CameraMic/dependencies/android/src/org/haxe/extension/cameramic/CameraMic.java#L69) the function. If you pass a directory name as an argument, the extension will create it if needed and store the images and the audios in that directory. That directory is stored in the path that returns the `Environment.getExternalStorageDirectory()` function (in my case is /storage/emulated/0, I have an LG G2 with no sd card).

So, in the test_project I call `CameraMic.appFilesDirectory = "/cameraMicTest";` and the `CameraMic.appFilesDirectory` value will be `/storage/emulated/0/cameraMicTes`.

hope this helps

**Comment by josuigoa** [comment]
I think [this](https://github.com/josuigoa/CameraMic/blob/master/CameraMic.hx#L148) was the reason why flash app was crashing. I tried the test_project targeting flash and it doesn't crash.

**Comment by ashes999** [comment]
That's great. Thanks for fixing it.

**Comment by ashes999** [comment]
I think this issue can be closed now. Thanks!
