### ISSUE TITLE
JNI Exception on Android

### ISSUE THREAD

**Issue by ashes999** [josuigoa/CameraMic#6]
Hi,

I have an app where I've embedded recording inside one of many scenes, and I allow the user to change scenes by swiping left and right.

I noticed this workflow generates a crash:

- Go to recording scene
- Start recording (but don't stop recording)
- Switch to another scene
- Switch back to the recording scene
- Start recording again

This is presumably because the recording device is already occupied. Since the class is static, it's not automatically destroyed when I change states.

Here's what the log files say:

> could not get audio input for record source 1
> audio source is not initialized
> start failed: -2147483648
> Java.lang.RuntimeException: start failed
>     at android.media.MediaReorder.native_start(Native Method)
> ...
> JNI Exception

I assume the work-around for this is to store and detect if the user is recording, and if so, force a stop recording when the scene changes.

**Comment by josuigoa** [comment]
I think that's the trick, yes. Store if it is recording and check it when you change the scene. Or do you need to continue recording while you set the scene?

**Comment by ashes999** [comment]
No, this workflow is fine for me. I stop the recording behind the scenes if the scene disposes.

Are the recording files automatically cleaned up at some point, or do they stay on the device forever? :)

**Comment by josuigoa** [comment]
if you use this line `sys.FileSystem.deleteFile(_audioPath);` with your audio paths, it won't be there forever ;)

**Comment by ashes999** [comment]
Uhoh. This really should be mentioned in the readme somewhere.

- If I want to keep only the most recent recording, the recording callback should delete the old file before assigning the new audio path
- If I want to delete all recordings when the app loses focus, I need to store all the recording files somewhere and delete them when my app shuts down.

Is that right?

**Comment by josuigoa** [comment]
yes, that is right. This is how my callback function looks like in another app:

`function onRecordAudioClick(me:MouseEvent):Void
	{
		if (_audioPath != null && sys.FileSystem.exists(_audioPath))
			sys.FileSystem.deleteFile(_audioPath);
      .....
`
is this enough or do you propose some way to do it at the extension?

**Comment by ashes999** [comment]
That's enough to get it working. It would be better if I could specify this in a parameter somewhere, but this will do very nicely.

**Comment by josuigoa** [comment]
Ok! It's a good idea to specify in a parameter, I'll do that, thank you!
